name: Hundun
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [assigned, opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build
        working-directory: ./hundun
        run: |
          cargo build --verbose
          cargo fmt --all -- --check
          cargo clippy -- -D warnings